spring.application.name=Shibakamio2026

spring.datasource.url=jdbc:postgresql://localhost:5432/shibakamio2026db

spring.datasource.username=postgres

spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.thymeleaf.cache=false
# テンプレート探索パス
spring.thymeleaf.prefix=classpath:/templates/
# テンプレート拡張子
spring.thymeleaf.suffix=.html

logging.level.org.apache.tomcat.util.net.Acceptor=OFF