-- 1. users
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT chk_users_email
        CHECK (email LIKE '%_@_%.__%')
);

-- 2. assets
CREATE TABLE IF NOT EXISTS assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    asset_name VARCHAR(50) NOT NULL,
    asset_type VARCHAR(50) NOT NULL,
    initial_balance DECIMAL(10,0) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_assets_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT chk_assets_initial_balance
        CHECK (initial_balance >= 0)
);

-- 3. categories
CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_categories_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT chk_categories_name
        CHECK (category_name <> ''),

    CONSTRAINT uq_categories_user_name
        UNIQUE (user_id, category_name)
);

-- 4. auto_transactions
CREATE TABLE IF NOT EXISTS auto_transactions (
    auto_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    transaction_type VARCHAR(10) NOT NULL,
    amount DECIMAL(10,0) NOT NULL,
    interval_type VARCHAR(10) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    is_enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_auto_transactions_asset
        FOREIGN KEY (asset_id)
        REFERENCES assets(asset_id),

    CONSTRAINT fk_auto_transactions_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id),

    CONSTRAINT chk_auto_transactions_type
        CHECK (transaction_type IN ('INCOME', 'EXPENSE')),

    CONSTRAINT chk_auto_transactions_amount
        CHECK (amount > 0),

    CONSTRAINT chk_auto_transactions_interval
        CHECK (interval_type IN ('WEEKLY', 'MONTHLY', 'YEARLY')),

    CONSTRAINT chk_auto_transactions_date
        CHECK (end_date IS NULL OR start_date <= end_date)
);

-- 5. scheduled_transactions
CREATE TABLE IF NOT EXISTS scheduled_transactions (
    scheduled_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auto_transaction_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    transaction_type VARCHAR(10) NOT NULL,
    scheduled_date DATE NOT NULL,
    amount DECIMAL(10,0) NOT NULL,
    status VARCHAR(20) NOT NULL,
    memo VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_scheduled_transactions_auto
        FOREIGN KEY (auto_transaction_id)
        REFERENCES auto_transactions(auto_transaction_id),

    CONSTRAINT fk_scheduled_transactions_asset
        FOREIGN KEY (asset_id)
        REFERENCES assets(asset_id),

    CONSTRAINT fk_scheduled_transactions_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id),

    CONSTRAINT chk_scheduled_transactions_type
        CHECK (transaction_type IN ('INCOME', 'EXPENSE')),

    CONSTRAINT chk_scheduled_transactions_amount
        CHECK (amount > 0),

    CONSTRAINT chk_scheduled_transactions_status
        CHECK (status IN ('PLANNED', 'PENDING_CONFIRMATION', 'CONFIRMED', 'CANCELED'))
);

-- 6. transactions
CREATE TABLE IF NOT EXISTS transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    scheduled_transaction_id BIGINT UNIQUE,

    transaction_type VARCHAR(10) NOT NULL,
    transaction_date DATE NOT NULL,

    amount DECIMAL(10,0) NOT NULL,

    transaction_content VARCHAR,
    business_partner VARCHAR,
    transaction_method VARCHAR,
    payment_type VARCHAR,
    user_name VARCHAR,

    transaction_number VARCHAR,

    memo VARCHAR,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_transactions_asset
        FOREIGN KEY (asset_id)
        REFERENCES assets(asset_id),

    CONSTRAINT fk_transactions_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id),

    CONSTRAINT fk_transactions_scheduled
        FOREIGN KEY (scheduled_transaction_id)
        REFERENCES scheduled_transactions(scheduled_transaction_id),

    CONSTRAINT chk_transactions_type
        CHECK (transaction_type IN ('INCOME', 'EXPENSE')),

    CONSTRAINT chk_transactions_amount
        CHECK (amount > 0)
);

-- 7. transfers
CREATE TABLE IF NOT EXISTS transfers (
    transfer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_asset_id BIGINT NOT NULL,
    to_asset_id BIGINT NOT NULL,
    amount DECIMAL(10,0) NOT NULL,
    transfer_date DATE NOT NULL,
    external_transaction_no VARCHAR,
    source_content VARCHAR,
    memo VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_transfers_from_asset
        FOREIGN KEY (from_asset_id)
        REFERENCES assets(asset_id),

    CONSTRAINT fk_transfers_to_asset
        FOREIGN KEY (to_asset_id)
        REFERENCES assets(asset_id),

    CONSTRAINT chk_transfers_amount
        CHECK (amount > 0),

    CONSTRAINT chk_transfers_different_assets
        CHECK (from_asset_id <> to_asset_id)
);